const express = require("express")
const router = express.Router()
const { createAccessory,deleteAccessory,getAccessoryByGallery,updateAccessory,deleteAccessoryFromRenter,getAccessoryRentersDetails} = require("../Controllers/AccessoryController")

router.post("/createAccessory",createAccessory)
router.delete("/deleteAccessory",deleteAccessory)
router.get("/getAccessoryByGallery/:galery",getAccessoryByGallery)
router.get("/getAccessoryRentersDetails/:accessoryId",getAccessoryRentersDetails)
router.put("/updateAccessory/:id",updateAccessory)
router.put("/deleteAccessoryFromRenter/:renterid",deleteAccessoryFromRenter)
